# Generated by Django 4.1.5 on 2023-02-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='наименование')),
                ('title_kk', models.CharField(max_length=150, null=True, verbose_name='наименование')),
            ],
        ),
        migrations.CreateModel(
            name='AbstractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(null=True, verbose_name='создан')),
                ('create_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='кем создан')),
                ('change_date', models.DateTimeField(null=True, verbose_name='изменен')),
                ('change_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='кем изменен')),
            ],
        ),
    ]
