# Generated by Django 4.1.5 on 2023-02-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractmodel',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='изменен'),
        ),
        migrations.AlterField(
            model_name='abstractmodel',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='создан'),
        ),
    ]
