# Generated by Django 4.1.5 on 2023-01-31 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ('date_enter', 'number'), 'verbose_name': 'отпускное удостоверение', 'verbose_name_plural': 'отпускные удостоверения'},
        ),
    ]
