# Generated by Django 4.1.5 on 2023-01-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='change_date',
            field=models.DateTimeField(verbose_name='изменен'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='create_date',
            field=models.DateTimeField(verbose_name='создан'),
        ),
    ]
