# Generated by Django 4.1.5 on 2023-01-17 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_holiday_change_date_alter_holiday_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='change_date',
            field=models.DateTimeField(null=True, verbose_name='изменен'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='change_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='change_user', to=settings.AUTH_USER_MODEL, verbose_name='кем изменен'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='create_date',
            field=models.DateTimeField(null=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='кем создан'),
        ),
    ]
