# Generated by Django 4.1.5 on 2023-01-18 02:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_degree'),
        ('main', '0003_alter_holiday_change_date_alter_holiday_change_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ('number', 'date_enter'), 'verbose_name': 'отпуск', 'verbose_name_plural': 'отпуска'},
        ),
        migrations.AddField(
            model_name='holiday',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата конец'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='date_enter',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата выдачи'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начало'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dictionaries.degree', verbose_name='звание'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='job',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='place',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='место выезда'),
        ),
    ]
